title: Homepage
description: realationship of relationship
url: "https://hxypqr.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM

collections:
  research:
    output: true
    permalink: /research/:name
